@startuml
!pragma layout smetana

title Reflexive Graph

circle "0" as V0
circle "1" as V1
circle "2" as V2
circle "3" as V3
circle "4" as V4

V0 -u-> V0
V1 -u-> V1
V2 -u-> V2
V3 -u-> V3
V4 -u-> V4

V0 --> V1
V0 --> V4
V1 --> V2
V1 --> V3
V2 --> V3
V3 --> V4
V4 --> V0

@enduml